<?xml version="1.0" encoding="UTF-8"?>
<definitions name="base"
 targetNamespace="base"
 xmlns:tns="base"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:srrc="http://www.srrc.org.cn"
 xmlns:ns1="base"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:HTTP="http://schemas.xmlsoap.org/wsdl/http/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="http://www.srrc.org.cn"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:srrc="http://www.srrc.org.cn"
  xmlns:ns1="base"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="base"/>
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
  <complexType name="MonitorHeader"><!-- srrc__MonitorHeader -->
   <sequence>
     <element ref="srrc:TransId" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__TransId -->
     <element ref="srrc:BizKey" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__BizKey -->
     <element ref="srrc:PSCode" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__PSCode -->
     <element ref="srrc:BSCode" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__BSCode -->
     <element ref="srrc:appCode" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__appCode -->
     <element ref="srrc:appName" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__appName -->
     <element ref="srrc:platFormCode" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__platFormCode -->
     <element ref="srrc:platFormName" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__platFormName -->
     <element ref="srrc:resCode1" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__resCode1 -->
     <element ref="srrc:resCode2" minOccurs="0" maxOccurs="1"/><!-- srrc__MonitorHeader::srrc__resCode2 -->
   </sequence>
  </complexType>
  <complexType name="ProviderResponse"><!-- srrc__ProviderResponse -->
   <sequence>
     <element ref="srrc:bizResCd" minOccurs="0" maxOccurs="1"/><!-- srrc__ProviderResponse::srrc__bizResCd -->
     <element ref="srrc:bizResText" minOccurs="0" maxOccurs="1"/><!-- srrc__ProviderResponse::srrc__bizResText -->
   </sequence>
  </complexType>
  <complexType name="item"><!-- srrc__item -->
   <sequence>
     <element ref="srrc:paraname" minOccurs="0" maxOccurs="1"/><!-- srrc__item::srrc__paraname -->
     <element ref="srrc:paravalue" minOccurs="0" maxOccurs="1"/><!-- srrc__item::srrc__paravalue -->
   </sequence>
  </complexType>
  <complexType name="array-items"><!-- srrc__array_items -->
   <sequence>
     <element ref="srrc:item" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__array_items::__sizeitem -->
   </sequence>
  </complexType>
  <complexType name="groupitem"><!-- srrc__groupitem -->
   <sequence>
     <element ref="srrc:groupid" minOccurs="0" maxOccurs="1"/><!-- srrc__groupitem::srrc__groupid -->
     <element ref="srrc:items" minOccurs="0" maxOccurs="1"/><!-- srrc__groupitem::srrc__items -->
   </sequence>
  </complexType>
  <complexType name="array-groupitems"><!-- srrc__array_groupitems -->
   <sequence>
     <element ref="srrc:groupitem" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__array_groupitems::__sizegroupitem -->
   </sequence>
  </complexType>
  <complexType name="equpara"><!-- srrc__equpara -->
   <sequence>
     <element ref="srrc:items" minOccurs="0" maxOccurs="1"/><!-- srrc__equpara::srrc__items -->
     <element ref="srrc:groupitems" minOccurs="0" maxOccurs="1"/><!-- srrc__equpara::srrc__groupitems -->
   </sequence>
  </complexType>
  <complexType name="exinfo"><!-- srrc__exinfo -->
   <sequence>
     <element ref="srrc:items" minOccurs="0" maxOccurs="1"/><!-- srrc__exinfo::srrc__items -->
   </sequence>
  </complexType>
  <complexType name="outputchannel"><!-- srrc__outputchannel -->
   <sequence>
     <element ref="srrc:mode" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__mode -->
     <element ref="srrc:datachannel" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__datachannel -->
     <element ref="srrc:host" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__host -->
     <element ref="srrc:port" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__port -->
     <element ref="srrc:stc" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__stc -->
     <element ref="srrc:password" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__password -->
     <element ref="srrc:user" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__user -->
     <element ref="srrc:file" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__file -->
     <element ref="srrc:exinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__outputchannel::srrc__exinfo -->
   </sequence>
  </complexType>
  <complexType name="error"><!-- srrc__error -->
   <sequence>
     <element ref="srrc:type" minOccurs="0" maxOccurs="1"/><!-- srrc__error::srrc__type -->
     <element ref="srrc:code" minOccurs="0" maxOccurs="1"/><!-- srrc__error::srrc__code -->
     <element ref="srrc:text" minOccurs="0" maxOccurs="1"/><!-- srrc__error::srrc__text -->
   </sequence>
  </complexType>
  <complexType name="requestbody"><!-- srrc__requestbody -->
   <sequence>
     <element ref="srrc:appid" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__appid -->
     <element ref="srrc:userid" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__userid -->
     <element ref="srrc:priority" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__priority -->
     <element ref="srrc:executetime" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__executetime -->
     <element ref="srrc:mfid" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__mfid -->
     <element ref="srrc:equid" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__equid -->
     <element ref="srrc:equpara" minOccurs="1" maxOccurs="1"/><!-- srrc__requestbody::srrc__equpara -->
     <element ref="srrc:exinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__exinfo -->
     <element ref="srrc:outputchannel" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__outputchannel -->
     <element ref="srrc:feature" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__feature -->
     <element ref="srrc:taskid" minOccurs="0" maxOccurs="1"/><!-- srrc__requestbody::srrc__taskid -->
   </sequence>
  </complexType>
  <complexType name="listitem"><!-- srrc__listitem -->
   <sequence>
     <element ref="srrc:display" minOccurs="0" maxOccurs="1"/><!-- srrc__listitem::srrc__display -->
     <element ref="srrc:val" minOccurs="0" maxOccurs="1"/><!-- srrc__listitem::srrc__val -->
   </sequence>
  </complexType>
  <complexType name="listitems"><!-- srrc__listitems -->
   <sequence>
     <element ref="srrc:listitem" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__listitems::__sizeenum -->
   </sequence>
  </complexType>
  <complexType name="range"><!-- srrc__range -->
   <sequence>
     <element ref="srrc:startval" minOccurs="0" maxOccurs="1"/><!-- srrc__range::srrc__startval -->
     <element ref="srrc:stopval" minOccurs="0" maxOccurs="1"/><!-- srrc__range::srrc__stopval -->
   </sequence>
  </complexType>
  <complexType name="parameter"><!-- srrc__parameter -->
   <sequence>
     <element ref="srrc:name" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__name -->
     <element ref="srrc:type" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__type -->
     <element ref="srrc:advanced" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__advanced -->
     <element ref="srrc:category" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__category -->
     <element ref="srrc:defaultvalue" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__defaultvalue -->
     <element ref="srrc:description" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__description -->
     <element ref="srrc:displayname" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__displayname -->
     <element ref="srrc:isbrowsable" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__isbrowsable -->
     <element ref="srrc:selectonly" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__selectonly -->
     <element ref="srrc:isreadonly" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__isreadonly -->
     <element ref="srrc:isgroupset" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__isgroupset -->
     <element ref="srrc:issubchannelset" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__issubchannelset -->
     <element ref="srrc:other" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__other -->
     <element ref="srrc:range" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__range -->
     <element ref="srrc:listitems" minOccurs="0" maxOccurs="1"/><!-- srrc__parameter::srrc__listitems -->
   </sequence>
  </complexType>
  <complexType name="input"><!-- srrc__input -->
   <sequence>
     <element ref="srrc:parameter" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__input::__sizeparameter -->
   </sequence>
  </complexType>
  <complexType name="feature"><!-- srrc__feature -->
   <sequence>
     <element ref="srrc:code" minOccurs="0" maxOccurs="1"/><!-- srrc__feature::srrc__code -->
     <element ref="srrc:input" minOccurs="0" maxOccurs="1"/><!-- srrc__feature::srrc__input -->
   </sequence>
  </complexType>
  <complexType name="featurelist"><!-- srrc__featurelist -->
   <sequence>
     <element ref="srrc:feature" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__featurelist::__sizefeature -->
   </sequence>
  </complexType>
  <complexType name="task"><!-- srrc__task -->
   <sequence>
     <element ref="srrc:taskid" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__taskid -->
     <element ref="srrc:userid" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__userid -->
     <element ref="srrc:feature" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__feature -->
     <element ref="srrc:appid" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__appid -->
     <element ref="srrc:stc" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__stc -->
     <element ref="srrc:exinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__task::srrc__exinfo -->
   </sequence>
  </complexType>
  <complexType name="tasklist"><!-- srrc__tasklist -->
   <sequence>
     <element ref="srrc:task" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__tasklist::__sizetask -->
   </sequence>
  </complexType>
  <complexType name="equipment"><!-- srrc__equipment -->
   <sequence>
     <element ref="srrc:equid" minOccurs="0" maxOccurs="1"/><!-- srrc__equipment::srrc__equid -->
     <element ref="srrc:equname" minOccurs="0" maxOccurs="1"/><!-- srrc__equipment::srrc__equname -->
     <element ref="srrc:exinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__equipment::srrc__exinfo -->
     <element ref="srrc:state" minOccurs="0" maxOccurs="1"/><!-- srrc__equipment::srrc__state -->
     <element ref="srrc:tasklist" minOccurs="0" maxOccurs="1"/><!-- srrc__equipment::srrc__tasklist -->
   </sequence>
  </complexType>
  <complexType name="equlist"><!-- srrc__equlist -->
   <sequence>
     <element ref="srrc:equipment" minOccurs="0" maxOccurs="1"/><!-- srrc__equlist::srrc__equipment -->
   </sequence>
  </complexType>
  <complexType name="exenviinfos"><!-- srrc__exenviinfos -->
   <sequence>
     <element ref="srrc:item" minOccurs="0" maxOccurs="unbounded"/><!-- srrc__exenviinfos::__sizeitem -->
   </sequence>
  </complexType>
  <complexType name="enviinfo"><!-- srrc__enviinfo -->
   <sequence>
     <element ref="srrc:current" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__current -->
     <element ref="srrc:voltage" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__voltage -->
     <element ref="srrc:temperature" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__temperature -->
     <element ref="srrc:humidity" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__humidity -->
     <element ref="srrc:gatingalarm" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__gatingalarm -->
     <element ref="srrc:smokealarm" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__smokealarm -->
     <element ref="srrc:floodingalarm" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__floodingalarm -->
     <element ref="srrc:powerfailurealarm" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__powerfailurealarm -->
     <element ref="srrc:masterswitch" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__masterswitch -->
     <element ref="srrc:airconditionerswitch" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__airconditionerswitch -->
     <element ref="srrc:lightingswitch" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__lightingswitch -->
     <element ref="srrc:equipmentswitch" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__equipmentswitch -->
     <element ref="srrc:exenviinfos" minOccurs="0" maxOccurs="1"/><!-- srrc__enviinfo::srrc__exenviinfos -->
   </sequence>
  </complexType>
  <complexType name="result"><!-- srrc__result -->
   <sequence>
     <element ref="srrc:appid" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__appid -->
     <element ref="srrc:userid" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__userid -->
     <element ref="srrc:priority" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__priority -->
     <element ref="srrc:executetime" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__executetime -->
     <element ref="srrc:mfid" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__mfid -->
     <element ref="srrc:equid" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equid -->
     <element ref="srrc:equpara" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equpara -->
     <element ref="srrc:taskid" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__taskid -->
     <element ref="srrc:exinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__exinfo -->
     <element ref="srrc:outputchannel" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__outputchannel -->
     <element ref="srrc:equimanu" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equimanu -->
     <element ref="srrc:equmodel" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equmodel -->
     <element ref="srrc:equname" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equname -->
     <element ref="srrc:equsn" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equsn -->
     <element ref="srrc:equstatus" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equstatus -->
     <element ref="srrc:equtype" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equtype -->
     <element ref="srrc:host" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__host -->
     <element ref="srrc:port" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__port -->
     <element ref="srrc:maxtasknumber" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__maxtasknumber -->
     <element ref="srrc:featurelist" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__featurelist -->
     <element ref="srrc:mfname" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__mfname -->
     <element ref="srrc:longitude" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__longitude -->
     <element ref="srrc:latitude" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__latitude -->
     <element ref="srrc:altitude" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__altitude -->
     <element ref="srrc:speed" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__speed -->
     <element ref="srrc:direction" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__direction -->
     <element ref="srrc:compass" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__compass -->
     <element ref="srrc:gpsnum" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__gpsnum -->
     <element ref="srrc:magneticdeclination" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__magneticdeclination -->
     <element ref="srrc:equlist" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__equlist -->
     <element ref="srrc:enviinfo" minOccurs="0" maxOccurs="1"/><!-- srrc__result::srrc__enviinfo -->
   </sequence>
  </complexType>
  <complexType name="responsebody"><!-- srrc__responsebody -->
   <sequence>
     <element ref="srrc:result" minOccurs="0" maxOccurs="1"/><!-- srrc__responsebody::srrc__result -->
     <element ref="srrc:error" minOccurs="0" maxOccurs="1"/><!-- srrc__responsebody::srrc__error -->
   </sequence>
  </complexType>
  <!-- operation response element -->
  <element name="responsebody" type="srrc:responsebody"/>
  <element name="TransId" type="xsd:string"/>
  <element name="BizKey" type="xsd:string"/>
  <element name="PSCode" type="xsd:string"/>
  <element name="BSCode" type="xsd:string"/>
  <element name="appCode" type="xsd:string"/>
  <element name="appName" type="xsd:string"/>
  <element name="platFormCode" type="xsd:string"/>
  <element name="platFormName" type="xsd:string"/>
  <element name="resCode1" type="xsd:string"/>
  <element name="resCode2" type="xsd:string"/>
  <element name="bizResCd" type="xsd:string"/>
  <element name="bizResText" type="xsd:string"/>
  <element name="paraname" type="xsd:string"/>
  <element name="paravalue" type="xsd:string"/>
  <element name="item" type="srrc:item"/>
  <element name="groupid" type="xsd:string"/>
  <element name="items" type="srrc:array-items"/>
  <element name="groupitem" type="srrc:groupitem"/>
  <element name="groupitems" type="srrc:array-groupitems"/>
  <element name="mode" type="xsd:string"/>
  <element name="datachannel" type="xsd:string"/>
  <element name="host" type="xsd:string"/>
  <element name="port" type="xsd:string"/>
  <element name="stc" type="xsd:string"/>
  <element name="password" type="xsd:string"/>
  <element name="user" type="xsd:string"/>
  <element name="file" type="xsd:string"/>
  <element name="exinfo" type="srrc:exinfo"/>
  <element name="type" type="xsd:string"/>
  <element name="code" type="xsd:string"/>
  <element name="text" type="xsd:string"/>
  <element name="appid" type="xsd:string"/>
  <element name="userid" type="xsd:string"/>
  <element name="priority" type="xsd:string"/>
  <element name="executetime" type="xsd:string"/>
  <element name="mfid" type="xsd:string"/>
  <element name="equid" type="xsd:string"/>
  <element name="equpara" type="srrc:equpara"/>
  <element name="outputchannel" type="srrc:outputchannel"/>
  <element name="feature" type="xsd:string"/>
  <element name="taskid" type="xsd:string"/>
  <element name="display" type="xsd:string"/>
  <element name="val" type="xsd:string"/>
  <element name="listitem" type="srrc:listitem"/>
  <element name="startval" type="xsd:string"/>
  <element name="stopval" type="xsd:string"/>
  <element name="name" type="xsd:string"/>
  <element name="advanced" type="xsd:string"/>
  <element name="category" type="xsd:string"/>
  <element name="defaultvalue" type="xsd:string"/>
  <element name="description" type="xsd:string"/>
  <element name="displayname" type="xsd:string"/>
  <element name="isbrowsable" type="xsd:string"/>
  <element name="selectonly" type="xsd:string"/>
  <element name="isreadonly" type="xsd:string"/>
  <element name="isgroupset" type="xsd:string"/>
  <element name="issubchannelset" type="xsd:string"/>
  <element name="other" type="xsd:string"/>
  <element name="range" type="srrc:range"/>
  <element name="listitems" type="srrc:listitems"/>
  <element name="parameter" type="srrc:parameter"/>
  <element name="input" type="srrc:input"/>
  <element name="task" type="srrc:task"/>
  <element name="equname" type="xsd:string"/>
  <element name="state" type="xsd:string"/>
  <element name="tasklist" type="srrc:tasklist"/>
  <element name="equipment" type="srrc:equipment"/>
  <element name="current" type="xsd:string"/>
  <element name="voltage" type="xsd:string"/>
  <element name="temperature" type="xsd:string"/>
  <element name="humidity" type="xsd:string"/>
  <element name="gatingalarm" type="xsd:string"/>
  <element name="smokealarm" type="xsd:string"/>
  <element name="floodingalarm" type="xsd:string"/>
  <element name="powerfailurealarm" type="xsd:string"/>
  <element name="masterswitch" type="xsd:string"/>
  <element name="airconditionerswitch" type="xsd:string"/>
  <element name="lightingswitch" type="xsd:string"/>
  <element name="equipmentswitch" type="xsd:string"/>
  <element name="exenviinfos" type="srrc:exenviinfos"/>
  <element name="equimanu" type="xsd:string"/>
  <element name="equmodel" type="xsd:string"/>
  <element name="equsn" type="xsd:string"/>
  <element name="equstatus" type="xsd:string"/>
  <element name="equtype" type="xsd:string"/>
  <element name="maxtasknumber" type="xsd:string"/>
  <element name="featurelist" type="srrc:featurelist"/>
  <element name="mfname" type="xsd:string"/>
  <element name="longitude" type="xsd:string"/>
  <element name="latitude" type="xsd:string"/>
  <element name="altitude" type="xsd:string"/>
  <element name="speed" type="xsd:string"/>
  <element name="direction" type="xsd:string"/>
  <element name="compass" type="xsd:string"/>
  <element name="gpsnum" type="xsd:string"/>
  <element name="magneticdeclination" type="xsd:string"/>
  <element name="equlist" type="srrc:equlist"/>
  <element name="enviinfo" type="srrc:enviinfo"/>
  <element name="result" type="srrc:result"/>
  <element name="error" type="srrc:error"/>
  <element name="MonitorHeader" type="srrc:MonitorHeader"/>
  <element name="ProviderResponse" type="srrc:ProviderResponse"/>
  <element name="requestbody" type="srrc:requestbody"/>
 </schema>

 <schema targetNamespace="base"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:srrc="http://www.srrc.org.cn"
  xmlns:ns1="base"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://www.srrc.org.cn"/>
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<message name="RmbusBaseService">
 <part name="Body" element="srrc:requestbody"/><!-- __ns1__RmbusBaseService::srrc__requestbody -->
</message>

<message name="responsebody">
 <part name="Body" element="srrc:responsebody"/>
</message>

<message name="baseHeader">
 <part name="MonitorHeader" element="srrc:MonitorHeader"/>
 <part name="ProviderResponse" element="srrc:ProviderResponse"/>
</message>

<portType name="basePortType">
 <operation name="RmbusBaseService">
  <documentation>Service definition of function __ns1__RmbusBaseService</documentation>
  <input message="tns:RmbusBaseService"/>
  <output message="tns:responsebody"/>
 </operation>
</portType>

<binding name="base" type="tns:basePortType">
 <SOAP:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="RmbusBaseService">
  <SOAP:operation soapAction="B_Mscan"/>
  <input>
     <SOAP:body parts="Body" use="literal"/>
     <SOAP:header use="literal" message="tns:baseHeader" part="MonitorHeader"/>
  </input>
  <output>
     <SOAP:body parts="Body" use="literal"/>
     <SOAP:header use="literal" message="tns:baseHeader" part="ProviderResponse"/>
  </output>
 </operation>
</binding>

<service name="base">
 <documentation>gSOAP 2.8.27 generated service definition</documentation>
 <port name="base" binding="tns:base">
  <SOAP:address location="http://localhost:8182"/>
 </port>
</service>

</definitions>
