<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions name="Base" 
                   targetNamespace="http://www.srrc.org.cn"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:tns="http://www.srrc.org.cn"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl"
                  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">
  <wsdl:types>
    <xsd:schema xmlns:tns="http://www.srrc.org.cn" elementFormDefault="qualified" targetNamespace="http://www.srrc.org.cn">
      <xsd:complexType name="MonitorHeader">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="BSCode" nillable="true" type="xsd:string"/>
          <xsd:element minOccurs="0" name="BizKey" nillable="true" type="xsd:string"/>
          <xsd:element minOccurs="0" name="PSCode" nillable="true" type="xsd:string"/>
          <xsd:element minOccurs="0" name="TransId" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="MonitorHeader" nillable="true" type="tns:MonitorHeader"/>
      <xsd:complexType name="ProviderResponse">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="bizResCd" nillable="true" type="xsd:string"/>
          <xsd:element minOccurs="0" name="bizResText" nillable="true" type="xsd:string"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:element name="ProviderResponse" nillable="true" type="tns:ProviderResponse"/>
      <xsd:element name="B_PScan">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="input" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="B_PScanResponse">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element minOccurs="0" name="B_PScanResult" nillable="true" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
	</xsd:schema>
  </wsdl:types>
  <wsdl:message name="Base_B_PScan_InputMessage">
    <wsdl:part name="parameters" element="tns:B_PScan"/>
  </wsdl:message>
  <wsdl:message name="Base_B_PScan_InputMessage_Headers">
    <wsdl:part name="MonitorHeader" element="tns:MonitorHeader"/>
  </wsdl:message>
  <wsdl:message name="Base_B_PScan_OutputMessage">
    <wsdl:part name="parameters" element="tns:B_PScanResponse"/>
  </wsdl:message>
  <wsdl:message name="Base_B_PScan_OutputMessage_Headers">
    <wsdl:part name="ProviderResponse" element="tns:ProviderResponse"/>
  </wsdl:message>
  <wsdl:portType name="Base">
    <wsdl:operation name="B_PScan">
      <wsdl:input wsaw:Action="B_PScan" message="tns:Base_B_PScan_InputMessage"/>
      <wsdl:output wsaw:Action="B_PScanResponse" message="tns:Base_B_PScan_OutputMessage"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BasicHttpBinding_Base" type="tns:Base">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="B_PScan">
      <soap:operation soapAction="B_PScan" style="document"/>
      <wsdl:input>
        <soap:header message="tns:Base_B_PScan_InputMessage_Headers" part="MonitorHeader" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:header message="tns:Base_B_PScan_OutputMessage_Headers" part="ProviderResponse" use="literal"/>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Base">
    <wsdl:port name="BasicHttpBinding_Base" binding="tns:BasicHttpBinding_Base">
      <soap:address location="http://127.0.0.1:8182/41000001110003/TCI737/B_PScan"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>